//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModel
{
	/// <summary>
	/// Database       : ResturantDB
	/// Data Source    : .\SQLEXPRESS
	/// Server Version : 16.00.1150
	/// </summary>
	public partial class APIDB : LinqToDB.Data.DataConnection
	{
		public ITable<LoginHistoryTbl>   LoginHistoryTbls   { get { return this.GetTable<LoginHistoryTbl>(); } }
		public ITable<MenuCategoriesTbl> MenuCategoriesTbls { get { return this.GetTable<MenuCategoriesTbl>(); } }
		public ITable<MenuReviewTbl>     MenuReviewTbls     { get { return this.GetTable<MenuReviewTbl>(); } }
		public ITable<MenuTbl>           MenuTbls           { get { return this.GetTable<MenuTbl>(); } }
		public ITable<PasswordTbl>       PasswordTbls       { get { return this.GetTable<PasswordTbl>(); } }
		public ITable<UserSessionTbl>    UserSessionTbls    { get { return this.GetTable<UserSessionTbl>(); } }
		public ITable<UserTable>         UserTables         { get { return this.GetTable<UserTable>(); } }

		public APIDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public APIDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public APIDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public APIDB(DataOptions<APIDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="LoginHistoryTbl")]
	public partial class LoginHistoryTbl : BSPL.Domain.IEntity
	{
		[PrimaryKey, Identity   ] public long      Id           { get; set; } // bigint
		[Column,     NotNull    ] public string    UserId       { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    Password     { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public bool      IsSuccessful { get; set; } // bit
		[Column,        Nullable] public string    IpAddress    { get; set; } // nvarchar(max)
		[Column,        Nullable] public string    DeviceId     { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public DateTime  CreatedOn    { get; set; } // datetime
		[Column,        Nullable] public string    CreatedBy    { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? UpdatedOn    { get; set; } // datetime
		[Column,        Nullable] public string    UpdatedBy    { get; set; } // nvarchar(max)
	}

	[Table(Schema="dbo", Name="MenuCategoriesTbl")]
	public partial class MenuCategoriesTbl : BSPL.Domain.IEntity
	{
		[PrimaryKey, Identity   ] public long      Id          { get; set; } // bigint
		[Column,     NotNull    ] public string    EnglishName { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    HindiName   { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    Image       { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public long      ImageId     { get; set; } // bigint
		[Column,     NotNull    ] public DateTime  CreatedOn   { get; set; } // datetime
		[Column,        Nullable] public string    CreatedBy   { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? UpdatedOn   { get; set; } // datetime
		[Column,        Nullable] public string    UpdatedBy   { get; set; } // nvarchar(max)
	}

	[Table(Schema="dbo", Name="MenuReviewTbl")]
	public partial class MenuReviewTbl : BSPL.Domain.IEntity
	{
		[PrimaryKey, Identity   ] public long      Id        { get; set; } // bigint
		[Column,     NotNull    ] public long      UserId    { get; set; } // bigint
		[Column,     NotNull    ] public long      MenuId    { get; set; } // bigint
		[Column,     NotNull    ] public long      Rating    { get; set; } // bigint
		[Column,     NotNull    ] public string    Comment   { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public DateTime  CreatedOn { get; set; } // datetime
		[Column,        Nullable] public string    CreatedBy { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? UpdatedOn { get; set; } // datetime
		[Column,        Nullable] public string    UpdatedBy { get; set; } // nvarchar(max)
	}

	[Table(Schema="dbo", Name="MenuTbl")]
	public partial class MenuTbl : BSPL.Domain.IEntity
	{
		[PrimaryKey, Identity   ] public long      Id                 { get; set; } // bigint
		[Column,     NotNull    ] public long      CategoryId         { get; set; } // bigint
		[Column,     NotNull    ] public string    EnglishName        { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    HindiName          { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    EnglishDescription { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    HindiDescription   { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public long      Price              { get; set; } // bigint
		[Column,     NotNull    ] public string    Image              { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public long      ImageId            { get; set; } // bigint
		[Column,     NotNull    ] public bool      IsAvailable        { get; set; } // bit
		[Column,     NotNull    ] public bool      IsVeg              { get; set; } // bit
		[Column,     NotNull    ] public DateTime  CreatedOn          { get; set; } // datetime
		[Column,        Nullable] public string    CreatedBy          { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? UpdatedOn          { get; set; } // datetime
		[Column,        Nullable] public string    UpdatedBy          { get; set; } // nvarchar(max)
	}

	[Table(Schema="dbo", Name="PasswordTbl")]
	public partial class PasswordTbl : BSPL.Domain.IEntity
	{
		[PrimaryKey, Identity   ] public long      Id        { get; set; } // bigint
		[Column,     NotNull    ] public string    UserId    { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    Password  { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public DateTime  CreatedOn { get; set; } // datetime
		[Column,        Nullable] public string    CreatedBy { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? UpdatedOn { get; set; } // datetime
		[Column,        Nullable] public string    UpdatedBy { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? LastLogin { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="UserSessionTbl")]
	public partial class UserSessionTbl : BSPL.Domain.IEntity
	{
		[PrimaryKey, Identity   ] public long      Id        { get; set; } // bigint
		[Column,     NotNull    ] public int       UserId    { get; set; } // int
		[Column,     NotNull    ] public string    Username  { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    JwtToken  { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public DateTime  IssuedAt  { get; set; } // datetime
		[Column,        Nullable] public DateTime? ExpiresAt { get; set; } // datetime
		[Column,     NotNull    ] public bool      IsActive  { get; set; } // bit
		[Column,     NotNull    ] public DateTime  CreatedOn { get; set; } // datetime
		[Column,        Nullable] public string    CreatedBy { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? UpdatedOn { get; set; } // datetime
		[Column,        Nullable] public string    UpdatedBy { get; set; } // nvarchar(max)
	}

	[Table(Schema="dbo", Name="UserTable")]
	public partial class UserTable : BSPL.Domain.IEntity
	{
		[PrimaryKey, Identity   ] public long      Id           { get; set; } // bigint
		[Column,     NotNull    ] public string    FullName     { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    Email        { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public string    PasswordHash { get; set; } // nvarchar(max)
		[Column,        Nullable] public string    Phone        { get; set; } // nvarchar(20)
		[Column,        Nullable] public string    FullAddress  { get; set; } // nvarchar(max)
		[Column,        Nullable] public string    DeviceId     { get; set; } // nvarchar(max)
		[Column,        Nullable] public Guid?     JwtSessionId { get; set; } // uniqueidentifier
		[Column,     NotNull    ] public bool      IsActive     { get; set; } // bit
		[Column,     NotNull    ] public bool      IsDeleted    { get; set; } // bit
		[Column,     NotNull    ] public DateTime  CreatedOn    { get; set; } // datetime
		[Column,        Nullable] public string    CreatedBy    { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? UpdatedOn    { get; set; } // datetime
		[Column,        Nullable] public string    UpdatedBy    { get; set; } // nvarchar(max)
		[Column,        Nullable] public DateTime? LastLogin    { get; set; } // datetime
	}

	public static partial class TableExtensions
	{
		public static LoginHistoryTbl Find(this ITable<LoginHistoryTbl> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static MenuCategoriesTbl Find(this ITable<MenuCategoriesTbl> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static MenuReviewTbl Find(this ITable<MenuReviewTbl> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static MenuTbl Find(this ITable<MenuTbl> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static PasswordTbl Find(this ITable<PasswordTbl> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UserSessionTbl Find(this ITable<UserSessionTbl> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static UserTable Find(this ITable<UserTable> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
